// Généré par content/curriculum/generate.mjs depuis content/curriculum/*.csv — ne pas éditer.
// ignore_for_file: lines_longer_than_80_chars
part of 'pedagogy.dart';

const curriculumLevels = [
  CurriculumLevel(rank: 1, key: "sounds", name: "Sons et écoute", objective: "Reconnaître les sons de la langue"),
  CurriculumLevel(rank: 2, key: "letters", name: "Lettres et sons", objective: "Associer chaque lettre à son son"),
  CurriculumLevel(rank: 3, key: "syllables", name: "Syllabes", objective: "Découper et assembler des syllabes"),
  CurriculumLevel(rank: 4, key: "words", name: "Mots simples", objective: "Lire des mots courts et fréquents"),
  CurriculumLevel(rank: 5, key: "complex-sounds", name: "Sons complexes", objective: "Reconnaître les sons composés"),
  CurriculumLevel(rank: 6, key: "sentences", name: "Phrases et compréhension", objective: "Lire et comprendre de courtes phrases"),
];

const curriculumNodes = [
  SkillNode(id: "n-son-a", level: "sounds", title: "Le son /a/", order: 1, unlockedWhen: 0),
  SkillNode(id: "n-son-e", level: "sounds", title: "Le son /e/", order: 2, unlockedWhen: 1),
  SkillNode(id: "n-son-i", level: "sounds", title: "Le son /i/", order: 3, unlockedWhen: 2),
  SkillNode(id: "n-son-o", level: "sounds", title: "Le son /o/", order: 4, unlockedWhen: 3),
  SkillNode(id: "n-son-u", level: "sounds", title: "Le son /u/", order: 5, unlockedWhen: 4),
  SkillNode(id: "n-son-e-aigu", level: "sounds", title: "Le son /é/", order: 6, unlockedWhen: 5),
  SkillNode(id: "n-son-m", level: "letters", title: "Le son /m/", order: 7, unlockedWhen: 6),
  SkillNode(id: "n-son-p", level: "letters", title: "Le son /p/", order: 8, unlockedWhen: 7),
  SkillNode(id: "n-son-t", level: "letters", title: "Le son /t/", order: 9, unlockedWhen: 8),
  SkillNode(id: "n-son-s", level: "letters", title: "Le son /s/", order: 10, unlockedWhen: 9),
  SkillNode(id: "n-son-l", level: "letters", title: "Le son /l/", order: 11, unlockedWhen: 10),
  SkillNode(id: "n-son-r", level: "letters", title: "Le son /r/", order: 12, unlockedWhen: 11),
  SkillNode(id: "n-son-n", level: "letters", title: "Le son /n/", order: 13, unlockedWhen: 12),
  SkillNode(id: "n-son-d", level: "letters", title: "Le son /d/", order: 14, unlockedWhen: 13),
  SkillNode(id: "n-son-f", level: "letters", title: "Le son /f/", order: 15, unlockedWhen: 14),
  SkillNode(id: "n-son-v", level: "letters", title: "Le son /v/", order: 16, unlockedWhen: 15),
  SkillNode(id: "n-son-b", level: "letters", title: "Le son /b/", order: 17, unlockedWhen: 16),
  SkillNode(id: "n-son-j", level: "letters", title: "Le son /j/", order: 18, unlockedWhen: 17),
  SkillNode(id: "n-letters-bd", level: "letters", title: "b ou d ?", order: 19, unlockedWhen: 18),
  SkillNode(id: "n-letters-pq", level: "letters", title: "p ou q ?", order: 20, unlockedWhen: 19),
  SkillNode(id: "n-son-ch", level: "syllables", title: "Le son /ch/", order: 21, unlockedWhen: 20),
  SkillNode(id: "n-son-ou", level: "syllables", title: "Le son /ou/", order: 22, unlockedWhen: 21),
  SkillNode(id: "n-syl-ma", level: "syllables", title: "La syllabe « ma »", order: 23, unlockedWhen: 22),
  SkillNode(id: "n-syl-pa", level: "syllables", title: "La syllabe « pa »", order: 24, unlockedWhen: 23),
  SkillNode(id: "n-syl-ta", level: "syllables", title: "La syllabe « ta »", order: 25, unlockedWhen: 24),
  SkillNode(id: "n-syl-la", level: "syllables", title: "La syllabe « la »", order: 26, unlockedWhen: 25),
  SkillNode(id: "n-syl-mi", level: "syllables", title: "La syllabe « mi »", order: 27, unlockedWhen: 26),
  SkillNode(id: "n-syl-pi", level: "syllables", title: "La syllabe « pi »", order: 28, unlockedWhen: 27),
  SkillNode(id: "n-syl-ti", level: "syllables", title: "La syllabe « ti »", order: 29, unlockedWhen: 28),
  SkillNode(id: "n-syl-li", level: "syllables", title: "La syllabe « li »", order: 30, unlockedWhen: 29),
  SkillNode(id: "n-syl-mo", level: "syllables", title: "La syllabe « mo »", order: 31, unlockedWhen: 30),
  SkillNode(id: "n-syl-to", level: "syllables", title: "La syllabe « to »", order: 32, unlockedWhen: 31),
  SkillNode(id: "n-mot-maman", level: "words", title: "Le mot « maman »", order: 33, unlockedWhen: 32),
  SkillNode(id: "n-mot-papa", level: "words", title: "Le mot « papa »", order: 34, unlockedWhen: 33),
  SkillNode(id: "n-mot-livre", level: "words", title: "Le mot « livre »", order: 35, unlockedWhen: 34),
  SkillNode(id: "n-mot-ecole", level: "words", title: "Le mot « école »", order: 36, unlockedWhen: 35),
  SkillNode(id: "n-mot-maison", level: "words", title: "Le mot « maison »", order: 37, unlockedWhen: 36),
  SkillNode(id: "n-mot-ami", level: "words", title: "Le mot « ami »", order: 38, unlockedWhen: 37),
  SkillNode(id: "n-mot-chat", level: "words", title: "Le mot « chat »", order: 39, unlockedWhen: 38),
  SkillNode(id: "n-mot-lune", level: "words", title: "Le mot « lune »", order: 40, unlockedWhen: 39),
  SkillNode(id: "n-mot-fleur", level: "words", title: "Le mot « fleur »", order: 41, unlockedWhen: 40),
  SkillNode(id: "n-mot-velo", level: "words", title: "Le mot « vélo »", order: 42, unlockedWhen: 41),
  SkillNode(id: "n-son-oi", level: "complex-sounds", title: "Le son /oi/", order: 43, unlockedWhen: 42),
  SkillNode(id: "n-son-an", level: "complex-sounds", title: "Le son /an/", order: 44, unlockedWhen: 43),
  SkillNode(id: "n-son-on", level: "complex-sounds", title: "Le son /on/", order: 45, unlockedWhen: 44),
  SkillNode(id: "n-son-in", level: "complex-sounds", title: "Le son /in/", order: 46, unlockedWhen: 45),
  SkillNode(id: "n-son-eau", level: "complex-sounds", title: "Le son /eau/", order: 47, unlockedWhen: 46),
  SkillNode(id: "n-phrase-1", level: "sentences", title: "Phrase : « Le chat dort. »", order: 48, unlockedWhen: 47),
  SkillNode(id: "n-phrase-2", level: "sentences", title: "Phrase : « Papa lit un livre. »", order: 49, unlockedWhen: 48),
  SkillNode(id: "n-phrase-3", level: "sentences", title: "Phrase : « La lune est belle. »", order: 50, unlockedWhen: 49),
  SkillNode(id: "n-phrase-4", level: "sentences", title: "Phrase : « Maman aime les fleurs. »", order: 51, unlockedWhen: 50),
  SkillNode(id: "n-phrase-5", level: "sentences", title: "Phrase : « Je vais à l’école. »", order: 52, unlockedWhen: 51),
];

const curriculumLessons = [
  Lesson(id: "l-son-a", nodeId: "n-son-a", title: "Le son /a/", objective: "Reconnaître, entendre, associer et tracer le son /a/.", durationMin: 7),
  Lesson(id: "l-son-e", nodeId: "n-son-e", title: "Le son /e/", objective: "Reconnaître, entendre, associer et tracer le son /e/.", durationMin: 7),
  Lesson(id: "l-son-i", nodeId: "n-son-i", title: "Le son /i/", objective: "Reconnaître, entendre, associer et tracer le son /i/.", durationMin: 7),
  Lesson(id: "l-son-o", nodeId: "n-son-o", title: "Le son /o/", objective: "Reconnaître, entendre, associer et tracer le son /o/.", durationMin: 7),
  Lesson(id: "l-son-u", nodeId: "n-son-u", title: "Le son /u/", objective: "Reconnaître, entendre, associer et tracer le son /u/.", durationMin: 7),
  Lesson(id: "l-son-e-aigu", nodeId: "n-son-e-aigu", title: "Le son /é/", objective: "Reconnaître, entendre, associer et tracer le son /é/.", durationMin: 7),
  Lesson(id: "l-son-m", nodeId: "n-son-m", title: "Le son /m/", objective: "Reconnaître, entendre, associer et tracer le son /m/.", durationMin: 7),
  Lesson(id: "l-son-p", nodeId: "n-son-p", title: "Le son /p/", objective: "Reconnaître, entendre, associer et tracer le son /p/.", durationMin: 7),
  Lesson(id: "l-son-t", nodeId: "n-son-t", title: "Le son /t/", objective: "Reconnaître, entendre, associer et tracer le son /t/.", durationMin: 7),
  Lesson(id: "l-son-s", nodeId: "n-son-s", title: "Le son /s/", objective: "Reconnaître, entendre, associer et tracer le son /s/.", durationMin: 7),
  Lesson(id: "l-son-l", nodeId: "n-son-l", title: "Le son /l/", objective: "Reconnaître, entendre, associer et tracer le son /l/.", durationMin: 7),
  Lesson(id: "l-son-r", nodeId: "n-son-r", title: "Le son /r/", objective: "Reconnaître, entendre, associer et tracer le son /r/.", durationMin: 7),
  Lesson(id: "l-son-n", nodeId: "n-son-n", title: "Le son /n/", objective: "Reconnaître, entendre, associer et tracer le son /n/.", durationMin: 7),
  Lesson(id: "l-son-d", nodeId: "n-son-d", title: "Le son /d/", objective: "Reconnaître, entendre, associer et tracer le son /d/.", durationMin: 7),
  Lesson(id: "l-son-f", nodeId: "n-son-f", title: "Le son /f/", objective: "Reconnaître, entendre, associer et tracer le son /f/.", durationMin: 7),
  Lesson(id: "l-son-v", nodeId: "n-son-v", title: "Le son /v/", objective: "Reconnaître, entendre, associer et tracer le son /v/.", durationMin: 7),
  Lesson(id: "l-son-b", nodeId: "n-son-b", title: "Le son /b/", objective: "Reconnaître, entendre, associer et tracer le son /b/.", durationMin: 7),
  Lesson(id: "l-son-j", nodeId: "n-son-j", title: "Le son /j/", objective: "Reconnaître, entendre, associer et tracer le son /j/.", durationMin: 7),
  Lesson(id: "l-bd-1", nodeId: "n-letters-bd", title: "b ou d ?", objective: "Ne plus confondre b et d, les lettres en miroir.", durationMin: 6),
  Lesson(id: "l-pq-1", nodeId: "n-letters-pq", title: "p ou q ?", objective: "Ne plus confondre p et q, les lettres en miroir.", durationMin: 6),
  Lesson(id: "l-son-ch", nodeId: "n-son-ch", title: "Le son /ch/", objective: "Reconnaître, entendre, associer et tracer le son /ch/.", durationMin: 7),
  Lesson(id: "l-son-ou", nodeId: "n-son-ou", title: "Le son /ou/", objective: "Reconnaître, entendre, associer et tracer le son /ou/.", durationMin: 7),
  Lesson(id: "l-syl-ma", nodeId: "n-syl-ma", title: "La syllabe « ma »", objective: "Découper, entendre et assembler la syllabe « ma ».", durationMin: 7),
  Lesson(id: "l-syl-pa", nodeId: "n-syl-pa", title: "La syllabe « pa »", objective: "Découper, entendre et assembler la syllabe « pa ».", durationMin: 7),
  Lesson(id: "l-syl-ta", nodeId: "n-syl-ta", title: "La syllabe « ta »", objective: "Découper, entendre et assembler la syllabe « ta ».", durationMin: 7),
  Lesson(id: "l-syl-la", nodeId: "n-syl-la", title: "La syllabe « la »", objective: "Découper, entendre et assembler la syllabe « la ».", durationMin: 7),
  Lesson(id: "l-syl-mi", nodeId: "n-syl-mi", title: "La syllabe « mi »", objective: "Découper, entendre et assembler la syllabe « mi ».", durationMin: 7),
  Lesson(id: "l-syl-pi", nodeId: "n-syl-pi", title: "La syllabe « pi »", objective: "Découper, entendre et assembler la syllabe « pi ».", durationMin: 7),
  Lesson(id: "l-syl-ti", nodeId: "n-syl-ti", title: "La syllabe « ti »", objective: "Découper, entendre et assembler la syllabe « ti ».", durationMin: 7),
  Lesson(id: "l-syl-li", nodeId: "n-syl-li", title: "La syllabe « li »", objective: "Découper, entendre et assembler la syllabe « li ».", durationMin: 7),
  Lesson(id: "l-syl-mo", nodeId: "n-syl-mo", title: "La syllabe « mo »", objective: "Découper, entendre et assembler la syllabe « mo ».", durationMin: 7),
  Lesson(id: "l-syl-to", nodeId: "n-syl-to", title: "La syllabe « to »", objective: "Découper, entendre et assembler la syllabe « to ».", durationMin: 7),
  Lesson(id: "l-mot-maman", nodeId: "n-mot-maman", title: "Le mot « maman »", objective: "Lire, écouter, épeler et comprendre le mot « maman ».", durationMin: 8),
  Lesson(id: "l-mot-papa", nodeId: "n-mot-papa", title: "Le mot « papa »", objective: "Lire, écouter, épeler et comprendre le mot « papa ».", durationMin: 8),
  Lesson(id: "l-mot-livre", nodeId: "n-mot-livre", title: "Le mot « livre »", objective: "Lire, écouter, épeler et comprendre le mot « livre ».", durationMin: 8),
  Lesson(id: "l-mot-ecole", nodeId: "n-mot-ecole", title: "Le mot « école »", objective: "Lire, écouter, épeler et comprendre le mot « école ».", durationMin: 8),
  Lesson(id: "l-mot-maison", nodeId: "n-mot-maison", title: "Le mot « maison »", objective: "Lire, écouter, épeler et comprendre le mot « maison ».", durationMin: 8),
  Lesson(id: "l-mot-ami", nodeId: "n-mot-ami", title: "Le mot « ami »", objective: "Lire, écouter, épeler et comprendre le mot « ami ».", durationMin: 8),
  Lesson(id: "l-mot-chat", nodeId: "n-mot-chat", title: "Le mot « chat »", objective: "Lire, écouter, épeler et comprendre le mot « chat ».", durationMin: 8),
  Lesson(id: "l-mot-lune", nodeId: "n-mot-lune", title: "Le mot « lune »", objective: "Lire, écouter, épeler et comprendre le mot « lune ».", durationMin: 8),
  Lesson(id: "l-mot-fleur", nodeId: "n-mot-fleur", title: "Le mot « fleur »", objective: "Lire, écouter, épeler et comprendre le mot « fleur ».", durationMin: 8),
  Lesson(id: "l-mot-velo", nodeId: "n-mot-velo", title: "Le mot « vélo »", objective: "Lire, écouter, épeler et comprendre le mot « vélo ».", durationMin: 8),
  Lesson(id: "l-son-oi", nodeId: "n-son-oi", title: "Le son /oi/", objective: "Reconnaître, entendre, associer et tracer le son /oi/.", durationMin: 7),
  Lesson(id: "l-son-an", nodeId: "n-son-an", title: "Le son /an/", objective: "Reconnaître, entendre, associer et tracer le son /an/.", durationMin: 7),
  Lesson(id: "l-son-on", nodeId: "n-son-on", title: "Le son /on/", objective: "Reconnaître, entendre, associer et tracer le son /on/.", durationMin: 7),
  Lesson(id: "l-son-in", nodeId: "n-son-in", title: "Le son /in/", objective: "Reconnaître, entendre, associer et tracer le son /in/.", durationMin: 7),
  Lesson(id: "l-son-eau", nodeId: "n-son-eau", title: "Le son /eau/", objective: "Reconnaître, entendre, associer et tracer le son /eau/.", durationMin: 7),
  Lesson(id: "l-phrase-1", nodeId: "n-phrase-1", title: "Phrase : « Le chat dort. »", objective: "Écouter, lire et comprendre la phrase « Le chat dort. ».", durationMin: 8),
  Lesson(id: "l-phrase-2", nodeId: "n-phrase-2", title: "Phrase : « Papa lit un livre. »", objective: "Écouter, lire et comprendre la phrase « Papa lit un livre. ».", durationMin: 8),
  Lesson(id: "l-phrase-3", nodeId: "n-phrase-3", title: "Phrase : « La lune est belle. »", objective: "Écouter, lire et comprendre la phrase « La lune est belle. ».", durationMin: 8),
  Lesson(id: "l-phrase-4", nodeId: "n-phrase-4", title: "Phrase : « Maman aime les fleurs. »", objective: "Écouter, lire et comprendre la phrase « Maman aime les fleurs. ».", durationMin: 8),
  Lesson(id: "l-phrase-5", nodeId: "n-phrase-5", title: "Phrase : « Je vais à l’école. »", objective: "Écouter, lire et comprendre la phrase « Je vais à l’école. ».", durationMin: 8),
];

const curriculumItems = [
  PedagogyItem(id: "g-a", type: ItemType.grapheme, label: "a", phoneme: "a", syllables: []),
  PedagogyItem(id: "g-e", type: ItemType.grapheme, label: "e", phoneme: "e", syllables: []),
  PedagogyItem(id: "g-i", type: ItemType.grapheme, label: "i", phoneme: "i", syllables: []),
  PedagogyItem(id: "g-o", type: ItemType.grapheme, label: "o", phoneme: "o", syllables: []),
  PedagogyItem(id: "g-u", type: ItemType.grapheme, label: "u", phoneme: "u", syllables: []),
  PedagogyItem(id: "g-e-aigu", type: ItemType.grapheme, label: "é", phoneme: "é", syllables: []),
  PedagogyItem(id: "g-m", type: ItemType.grapheme, label: "m", phoneme: "m", syllables: []),
  PedagogyItem(id: "g-p", type: ItemType.grapheme, label: "p", phoneme: "p", syllables: []),
  PedagogyItem(id: "g-t", type: ItemType.grapheme, label: "t", phoneme: "t", syllables: []),
  PedagogyItem(id: "g-s", type: ItemType.grapheme, label: "s", phoneme: "s", syllables: []),
  PedagogyItem(id: "g-l", type: ItemType.grapheme, label: "l", phoneme: "l", syllables: []),
  PedagogyItem(id: "g-r", type: ItemType.grapheme, label: "r", phoneme: "r", syllables: []),
  PedagogyItem(id: "g-n", type: ItemType.grapheme, label: "n", phoneme: "n", syllables: []),
  PedagogyItem(id: "g-d", type: ItemType.grapheme, label: "d", phoneme: "d", syllables: []),
  PedagogyItem(id: "g-f", type: ItemType.grapheme, label: "f", phoneme: "f", syllables: []),
  PedagogyItem(id: "g-v", type: ItemType.grapheme, label: "v", phoneme: "v", syllables: []),
  PedagogyItem(id: "g-b", type: ItemType.grapheme, label: "b", phoneme: "b", syllables: []),
  PedagogyItem(id: "g-j", type: ItemType.grapheme, label: "j", phoneme: "j", syllables: []),
  PedagogyItem(id: "g-ch", type: ItemType.grapheme, label: "ch", phoneme: "ch", syllables: []),
  PedagogyItem(id: "g-ou", type: ItemType.grapheme, label: "ou", phoneme: "ou", syllables: []),
  PedagogyItem(id: "g-oi", type: ItemType.grapheme, label: "oi", phoneme: "oi", syllables: []),
  PedagogyItem(id: "g-an", type: ItemType.grapheme, label: "an", phoneme: "an", syllables: []),
  PedagogyItem(id: "g-on", type: ItemType.grapheme, label: "on", phoneme: "on", syllables: []),
  PedagogyItem(id: "g-in", type: ItemType.grapheme, label: "in", phoneme: "in", syllables: []),
  PedagogyItem(id: "g-eau", type: ItemType.grapheme, label: "eau", phoneme: "eau", syllables: []),
  PedagogyItem(id: "g-q", type: ItemType.grapheme, label: "q", phoneme: "k", syllables: []),
  PedagogyItem(id: "w-avion", type: ItemType.word, label: "avion", phoneme: "avion", syllables: ["a", "vi", "on"]),
  PedagogyItem(id: "w-doigt", type: ItemType.word, label: "doigt", phoneme: "doigt", syllables: ["doigt"]),
  PedagogyItem(id: "w-ecole", type: ItemType.word, label: "école", phoneme: "école", syllables: ["é", "co", "le"]),
  PedagogyItem(id: "w-papa", type: ItemType.word, label: "papa", phoneme: "papa", syllables: ["pa", "pa"]),
  PedagogyItem(id: "w-pomme", type: ItemType.word, label: "pomme", phoneme: "pomme", syllables: ["pom", "me"]),
  PedagogyItem(id: "w-poule", type: ItemType.word, label: "poule", phoneme: "poule", syllables: ["pou", "le"]),
  PedagogyItem(id: "w-cheval", type: ItemType.word, label: "cheval", phoneme: "cheval", syllables: ["che", "val"]),
  PedagogyItem(id: "w-chat", type: ItemType.word, label: "chat", phoneme: "chat", syllables: ["chat"]),
  PedagogyItem(id: "w-ballon", type: ItemType.word, label: "ballon", phoneme: "ballon", syllables: ["bal", "lon"]),
  PedagogyItem(id: "w-iguane", type: ItemType.word, label: "iguane", phoneme: "iguane", syllables: ["i", "gua", "ne"]),
  PedagogyItem(id: "w-banane", type: ItemType.word, label: "banane", phoneme: "banane", syllables: ["ba", "na", "ne"]),
  PedagogyItem(id: "w-ami", type: ItemType.word, label: "ami", phoneme: "ami", syllables: ["a", "mi"]),
  PedagogyItem(id: "w-nez", type: ItemType.word, label: "nez", phoneme: "nez", syllables: ["nez"]),
  PedagogyItem(id: "w-bebe", type: ItemType.word, label: "bébé", phoneme: "bébé", syllables: ["bé", "bé"]),
  PedagogyItem(id: "w-orange", type: ItemType.word, label: "orange", phoneme: "orange", syllables: ["o", "ran", "ge"]),
  PedagogyItem(id: "w-bateau", type: ItemType.word, label: "bateau", phoneme: "bateau", syllables: ["ba", "teau"]),
  PedagogyItem(id: "w-robot", type: ItemType.word, label: "robot", phoneme: "robot", syllables: ["ro", "bot"]),
  PedagogyItem(id: "w-fleur", type: ItemType.word, label: "fleur", phoneme: "fleur", syllables: ["fleur"]),
  PedagogyItem(id: "w-lapin", type: ItemType.word, label: "lapin", phoneme: "lapin", syllables: ["la", "pin"]),
  PedagogyItem(id: "w-lune", type: ItemType.word, label: "lune", phoneme: "lune", syllables: ["lu", "ne"]),
  PedagogyItem(id: "w-lion", type: ItemType.word, label: "lion", phoneme: "lion", syllables: ["li", "on"]),
  PedagogyItem(id: "w-jupe", type: ItemType.word, label: "jupe", phoneme: "jupe", syllables: ["ju", "pe"]),
  PedagogyItem(id: "w-velo", type: ItemType.word, label: "vélo", phoneme: "vélo", syllables: ["vé", "lo"]),
  PedagogyItem(id: "w-dodo", type: ItemType.word, label: "dodo", phoneme: "dodo", syllables: ["do", "do"]),
  PedagogyItem(id: "w-maison", type: ItemType.word, label: "maison", phoneme: "maison", syllables: ["mai", "son"]),
  PedagogyItem(id: "w-maman", type: ItemType.word, label: "maman", phoneme: "maman", syllables: ["ma", "man"]),
  PedagogyItem(id: "w-tortue", type: ItemType.word, label: "tortue", phoneme: "tortue", syllables: ["tor", "tue"]),
  PedagogyItem(id: "w-soleil", type: ItemType.word, label: "soleil", phoneme: "soleil", syllables: ["so", "leil"]),
  PedagogyItem(id: "w-poisson", type: ItemType.word, label: "poisson", phoneme: "poisson", syllables: ["pois", "son"]),
  PedagogyItem(id: "w-domino", type: ItemType.word, label: "domino", phoneme: "domino", syllables: ["do", "mi", "no"]),
  PedagogyItem(id: "w-bonbon", type: ItemType.word, label: "bonbon", phoneme: "bonbon", syllables: ["bon", "bon"]),
  PedagogyItem(id: "w-bon", type: ItemType.word, label: "bon", phoneme: "bon", syllables: ["bon"]),
  PedagogyItem(id: "w-don", type: ItemType.word, label: "don", phoneme: "don", syllables: ["don"]),
  PedagogyItem(id: "w-quatre", type: ItemType.word, label: "quatre", phoneme: "quatre", syllables: ["qua", "tre"]),
  PedagogyItem(id: "w-coq", type: ItemType.word, label: "coq", phoneme: "coq", syllables: ["coq"]),
  PedagogyItem(id: "w-loupe", type: ItemType.word, label: "loupe", phoneme: "loupe", syllables: ["lou", "pe"]),
  PedagogyItem(id: "w-livre", type: ItemType.word, label: "livre", phoneme: "livre", syllables: ["li", "vre"]),
  PedagogyItem(id: "s-ma", type: ItemType.syllable, label: "ma", phoneme: "ma", syllables: ["ma"]),
  PedagogyItem(id: "s-pa", type: ItemType.syllable, label: "pa", phoneme: "pa", syllables: ["pa"]),
  PedagogyItem(id: "s-mi", type: ItemType.syllable, label: "mi", phoneme: "mi", syllables: ["mi"]),
  PedagogyItem(id: "s-am", type: ItemType.syllable, label: "am", phoneme: "am", syllables: ["am"]),
  PedagogyItem(id: "s-ta", type: ItemType.syllable, label: "ta", phoneme: "ta", syllables: ["ta"]),
  PedagogyItem(id: "s-pi", type: ItemType.syllable, label: "pi", phoneme: "pi", syllables: ["pi"]),
  PedagogyItem(id: "s-ap", type: ItemType.syllable, label: "ap", phoneme: "ap", syllables: ["ap"]),
  PedagogyItem(id: "s-la", type: ItemType.syllable, label: "la", phoneme: "la", syllables: ["la"]),
  PedagogyItem(id: "s-ti", type: ItemType.syllable, label: "ti", phoneme: "ti", syllables: ["ti"]),
  PedagogyItem(id: "s-at", type: ItemType.syllable, label: "at", phoneme: "at", syllables: ["at"]),
  PedagogyItem(id: "s-li", type: ItemType.syllable, label: "li", phoneme: "li", syllables: ["li"]),
  PedagogyItem(id: "s-al", type: ItemType.syllable, label: "al", phoneme: "al", syllables: ["al"]),
  PedagogyItem(id: "s-mo", type: ItemType.syllable, label: "mo", phoneme: "mo", syllables: ["mo"]),
  PedagogyItem(id: "s-im", type: ItemType.syllable, label: "im", phoneme: "im", syllables: ["im"]),
  PedagogyItem(id: "s-ip", type: ItemType.syllable, label: "ip", phoneme: "ip", syllables: ["ip"]),
  PedagogyItem(id: "s-to", type: ItemType.syllable, label: "to", phoneme: "to", syllables: ["to"]),
  PedagogyItem(id: "s-it", type: ItemType.syllable, label: "it", phoneme: "it", syllables: ["it"]),
  PedagogyItem(id: "s-il", type: ItemType.syllable, label: "il", phoneme: "il", syllables: ["il"]),
  PedagogyItem(id: "s-om", type: ItemType.syllable, label: "om", phoneme: "om", syllables: ["om"]),
  PedagogyItem(id: "s-ot", type: ItemType.syllable, label: "ot", phoneme: "ot", syllables: ["ot"]),
  PedagogyItem(id: "x-naman", type: ItemType.word, label: "naman", phoneme: "naman", syllables: ["naman"]),
  PedagogyItem(id: "x-qapa", type: ItemType.word, label: "qapa", phoneme: "qapa", syllables: ["qapa"]),
  PedagogyItem(id: "x-tivre", type: ItemType.word, label: "tivre", phoneme: "tivre", syllables: ["tivre"]),
  PedagogyItem(id: "w-elephant", type: ItemType.word, label: "éléphant", phoneme: "éléphant", syllables: ["é", "lé", "phant"]),
  PedagogyItem(id: "x-ecole", type: ItemType.word, label: "ècole", phoneme: "ècole", syllables: ["ècole"]),
  PedagogyItem(id: "x-naison", type: ItemType.word, label: "naison", phoneme: "naison", syllables: ["naison"]),
  PedagogyItem(id: "x-omi", type: ItemType.word, label: "omi", phoneme: "omi", syllables: ["omi"]),
  PedagogyItem(id: "x-chot", type: ItemType.word, label: "chot", phoneme: "chot", syllables: ["chot"]),
  PedagogyItem(id: "x-tune", type: ItemType.word, label: "tune", phoneme: "tune", syllables: ["tune"]),
  PedagogyItem(id: "x-tleur", type: ItemType.word, label: "tleur", phoneme: "tleur", syllables: ["tleur"]),
  PedagogyItem(id: "x-uelo", type: ItemType.word, label: "uélo", phoneme: "uélo", syllables: ["uélo"]),
  PedagogyItem(id: "p-1", type: ItemType.sentence, label: "Le chat dort.", phoneme: "Le chat dort.", syllables: ["Le", "chat", "dort."]),
  PedagogyItem(id: "p-2", type: ItemType.sentence, label: "Papa lit un livre.", phoneme: "Papa lit un livre.", syllables: ["Pa-pa", "lit", "un", "li-vre."]),
  PedagogyItem(id: "p-3", type: ItemType.sentence, label: "La lune est belle.", phoneme: "La lune est belle.", syllables: ["La", "lu-ne", "est", "bel-le."]),
  PedagogyItem(id: "p-4", type: ItemType.sentence, label: "Maman aime les fleurs.", phoneme: "Maman aime les fleurs.", syllables: ["Ma-man", "ai-me", "les", "fleurs."]),
  PedagogyItem(id: "p-5", type: ItemType.sentence, label: "Je vais à l’école.", phoneme: "Je vais à l’école.", syllables: ["Je", "vais", "à", "l’é-co-le."]),
  PedagogyItem(id: "w-le", type: ItemType.word, label: "le", phoneme: "le", syllables: ["le"]),
  PedagogyItem(id: "w-dort", type: ItemType.word, label: "dort", phoneme: "dort", syllables: ["dort"]),
  PedagogyItem(id: "w-lit", type: ItemType.word, label: "lit", phoneme: "lit", syllables: ["lit"]),
  PedagogyItem(id: "w-un", type: ItemType.word, label: "un", phoneme: "un", syllables: ["un"]),
  PedagogyItem(id: "w-la", type: ItemType.word, label: "la", phoneme: "la", syllables: ["la"]),
  PedagogyItem(id: "w-est", type: ItemType.word, label: "est", phoneme: "est", syllables: ["est"]),
  PedagogyItem(id: "w-belle", type: ItemType.word, label: "belle", phoneme: "belle", syllables: ["bel", "le"]),
  PedagogyItem(id: "w-aime", type: ItemType.word, label: "aime", phoneme: "aime", syllables: ["ai", "me"]),
  PedagogyItem(id: "w-les", type: ItemType.word, label: "les", phoneme: "les", syllables: ["les"]),
  PedagogyItem(id: "w-fleurs", type: ItemType.word, label: "fleurs", phoneme: "fleurs", syllables: ["fleurs"]),
  PedagogyItem(id: "w-je", type: ItemType.word, label: "je", phoneme: "je", syllables: ["je"]),
  PedagogyItem(id: "w-vais", type: ItemType.word, label: "vais", phoneme: "vais", syllables: ["vais"]),
  PedagogyItem(id: "w-a", type: ItemType.word, label: "à", phoneme: "à", syllables: ["à"]),
];

const curriculumExercises = [
  Exercise(id: "e-son-a-1", lessonId: "l-son-a", type: ExerciseType.soundGrapheme, order: 1, phoneme: "a", cue: "a, comme dans avion", itemIds: ["g-a", "g-o"]),
  Exercise(id: "e-son-a-2", lessonId: "l-son-a", type: ExerciseType.wordRecognition, order: 2, correctItemId: "w-avion", itemIds: ["w-avion", "w-doigt", "w-ecole"]),
  Exercise(id: "e-son-a-3", lessonId: "l-son-a", type: ExerciseType.soundGrapheme, order: 3, phoneme: "a", cue: "a", itemIds: ["g-o", "g-a", "g-e"]),
  Exercise(id: "e-son-a-4", lessonId: "l-son-a", type: ExerciseType.wordRecognition, order: 4, correctItemId: "w-papa", itemIds: ["w-pomme", "w-poule", "w-papa"]),
  Exercise(id: "e-son-e-1", lessonId: "l-son-e", type: ExerciseType.soundGrapheme, order: 1, phoneme: "e", cue: "e, comme dans cheval", itemIds: ["g-e-aigu", "g-e"]),
  Exercise(id: "e-son-e-2", lessonId: "l-son-e", type: ExerciseType.wordRecognition, order: 2, correctItemId: "w-cheval", itemIds: ["w-chat", "w-ballon", "w-cheval"]),
  Exercise(id: "e-son-e-3", lessonId: "l-son-e", type: ExerciseType.soundGrapheme, order: 3, phoneme: "e", cue: "e", itemIds: ["g-e", "g-u", "g-e-aigu"]),
  Exercise(id: "e-son-i-1", lessonId: "l-son-i", type: ExerciseType.soundGrapheme, order: 1, phoneme: "i", cue: "i, comme dans iguane", itemIds: ["g-i", "g-e-aigu"]),
  Exercise(id: "e-son-i-2", lessonId: "l-son-i", type: ExerciseType.wordRecognition, order: 2, correctItemId: "w-iguane", itemIds: ["w-banane", "w-iguane", "w-ballon"]),
  Exercise(id: "e-son-i-3", lessonId: "l-son-i", type: ExerciseType.soundGrapheme, order: 3, phoneme: "i", cue: "i", itemIds: ["g-a", "g-e-aigu", "g-i"]),
  Exercise(id: "e-son-i-4", lessonId: "l-son-i", type: ExerciseType.wordRecognition, order: 4, correctItemId: "w-ami", itemIds: ["w-ami", "w-nez", "w-bebe"]),
  Exercise(id: "e-son-o-1", lessonId: "l-son-o", type: ExerciseType.soundGrapheme, order: 1, phoneme: "o", cue: "o, comme dans orange", itemIds: ["g-a", "g-o"]),
  Exercise(id: "e-son-o-2", lessonId: "l-son-o", type: ExerciseType.wordRecognition, order: 2, correctItemId: "w-orange", itemIds: ["w-orange", "w-banane", "w-bateau"]),
  Exercise(id: "e-son-o-3", lessonId: "l-son-o", type: ExerciseType.soundGrapheme, order: 3, phoneme: "o", cue: "o", itemIds: ["g-a", "g-o", "g-u"]),
  Exercise(id: "e-son-o-4", lessonId: "l-son-o", type: ExerciseType.wordRecognition, order: 4, correctItemId: "w-robot", itemIds: ["w-fleur", "w-lapin", "w-robot"]),
  Exercise(id: "e-son-u-1", lessonId: "l-son-u", type: ExerciseType.soundGrapheme, order: 1, phoneme: "u", cue: "u, comme dans lune", itemIds: ["g-u", "g-i"]),
  Exercise(id: "e-son-u-2", lessonId: "l-son-u", type: ExerciseType.wordRecognition, order: 2, correctItemId: "w-lune", itemIds: ["w-lion", "w-lapin", "w-lune"]),
  Exercise(id: "e-son-u-3", lessonId: "l-son-u", type: ExerciseType.soundGrapheme, order: 3, phoneme: "u", cue: "u", itemIds: ["g-u", "g-o", "g-i"]),
  Exercise(id: "e-son-u-4", lessonId: "l-son-u", type: ExerciseType.wordRecognition, order: 4, correctItemId: "w-jupe", itemIds: ["w-chat", "w-jupe", "w-bebe"]),
  Exercise(id: "e-son-e-aigu-1", lessonId: "l-son-e-aigu", type: ExerciseType.soundGrapheme, order: 1, phoneme: "é", cue: "é, comme dans école", itemIds: ["g-e", "g-e-aigu"]),
  Exercise(id: "e-son-e-aigu-2", lessonId: "l-son-e-aigu", type: ExerciseType.wordRecognition, order: 2, correctItemId: "w-ecole", itemIds: ["w-doigt", "w-ecole", "w-avion"]),
  Exercise(id: "e-son-e-aigu-3", lessonId: "l-son-e-aigu", type: ExerciseType.soundGrapheme, order: 3, phoneme: "é", cue: "é", itemIds: ["g-i", "g-e", "g-e-aigu"]),
  Exercise(id: "e-son-e-aigu-4", lessonId: "l-son-e-aigu", type: ExerciseType.wordRecognition, order: 4, correctItemId: "w-velo", itemIds: ["w-velo", "w-chat", "w-dodo"]),
  Exercise(id: "e-son-m-1", lessonId: "l-son-m", type: ExerciseType.soundGrapheme, order: 1, phoneme: "m", cue: "m, comme dans maison", itemIds: ["g-m", "g-n"]),
  Exercise(id: "e-son-m-2", lessonId: "l-son-m", type: ExerciseType.wordRecognition, order: 2, correctItemId: "w-maison", itemIds: ["w-maison", "w-ballon", "w-banane"]),
  Exercise(id: "e-son-m-3", lessonId: "l-son-m", type: ExerciseType.soundGrapheme, order: 3, phoneme: "m", cue: "m", itemIds: ["g-n", "g-m", "g-p"]),
  Exercise(id: "e-son-m-4", lessonId: "l-son-m", type: ExerciseType.wordRecognition, order: 4, correctItemId: "w-maman", itemIds: ["w-avion", "w-doigt", "w-maman"]),
  Exercise(id: "e-son-p-1", lessonId: "l-son-p", type: ExerciseType.soundGrapheme, order: 1, phoneme: "p", cue: "p, comme dans papa", itemIds: ["g-q", "g-p"]),
  Exercise(id: "e-son-p-2", lessonId: "l-son-p", type: ExerciseType.wordRecognition, order: 2, correctItemId: "w-papa", itemIds: ["w-bebe", "w-chat", "w-papa"]),
  Exercise(id: "e-son-p-3", lessonId: "l-son-p", type: ExerciseType.soundGrapheme, order: 3, phoneme: "p", cue: "p", itemIds: ["g-p", "g-b", "g-q"]),
  Exercise(id: "e-son-p-4", lessonId: "l-son-p", type: ExerciseType.wordRecognition, order: 4, correctItemId: "w-pomme", itemIds: ["w-doigt", "w-pomme", "w-avion"]),
  Exercise(id: "e-son-t-1", lessonId: "l-son-t", type: ExerciseType.soundGrapheme, order: 1, phoneme: "t", cue: "t, comme dans tortue", itemIds: ["g-t", "g-d"]),
  Exercise(id: "e-son-t-2", lessonId: "l-son-t", type: ExerciseType.wordRecognition, order: 2, correctItemId: "w-tortue", itemIds: ["w-banane", "w-tortue", "w-ballon"]),
  Exercise(id: "e-son-t-3", lessonId: "l-son-t", type: ExerciseType.soundGrapheme, order: 3, phoneme: "t", cue: "t", itemIds: ["g-l", "g-d", "g-t"]),
  Exercise(id: "e-son-t-4", lessonId: "l-son-t", type: ExerciseType.wordRecognition, order: 4, correctItemId: "w-bateau", itemIds: ["w-bateau", "w-ballon", "w-banane"]),
  Exercise(id: "e-son-s-1", lessonId: "l-son-s", type: ExerciseType.soundGrapheme, order: 1, phoneme: "s", cue: "s, comme dans soleil", itemIds: ["g-f", "g-s"]),
  Exercise(id: "e-son-s-2", lessonId: "l-son-s", type: ExerciseType.wordRecognition, order: 2, correctItemId: "w-soleil", itemIds: ["w-soleil", "w-ballon", "w-banane"]),
  Exercise(id: "e-son-s-3", lessonId: "l-son-s", type: ExerciseType.soundGrapheme, order: 3, phoneme: "s", cue: "s", itemIds: ["g-f", "g-s", "g-r"]),
  Exercise(id: "e-son-s-4", lessonId: "l-son-s", type: ExerciseType.wordRecognition, order: 4, correctItemId: "w-poisson", itemIds: ["w-pomme", "w-poule", "w-poisson"]),
  Exercise(id: "e-son-l-1", lessonId: "l-son-l", type: ExerciseType.soundGrapheme, order: 1, phoneme: "l", cue: "l, comme dans lion", itemIds: ["g-l", "g-t"]),
  Exercise(id: "e-son-l-2", lessonId: "l-son-l", type: ExerciseType.wordRecognition, order: 2, correctItemId: "w-lion", itemIds: ["w-bebe", "w-chat", "w-lion"]),
  Exercise(id: "e-son-l-3", lessonId: "l-son-l", type: ExerciseType.soundGrapheme, order: 3, phoneme: "l", cue: "l", itemIds: ["g-l", "g-r", "g-t"]),
  Exercise(id: "e-son-l-4", lessonId: "l-son-l", type: ExerciseType.wordRecognition, order: 4, correctItemId: "w-lune", itemIds: ["w-chat", "w-lune", "w-bebe"]),
  Exercise(id: "e-son-r-1", lessonId: "l-son-r", type: ExerciseType.soundGrapheme, order: 1, phoneme: "r", cue: "r, comme dans robot", itemIds: ["g-l", "g-r"]),
  Exercise(id: "e-son-r-2", lessonId: "l-son-r", type: ExerciseType.wordRecognition, order: 2, correctItemId: "w-robot", itemIds: ["w-doigt", "w-robot", "w-avion"]),
  Exercise(id: "e-son-r-3", lessonId: "l-son-r", type: ExerciseType.soundGrapheme, order: 3, phoneme: "r", cue: "r", itemIds: ["g-n", "g-l", "g-r"]),
  Exercise(id: "e-son-r-4", lessonId: "l-son-r", type: ExerciseType.wordRecognition, order: 4, correctItemId: "w-fleur", itemIds: ["w-fleur", "w-avion", "w-doigt"]),
  Exercise(id: "e-son-n-1", lessonId: "l-son-n", type: ExerciseType.soundGrapheme, order: 1, phoneme: "n", cue: "n, comme dans nez", itemIds: ["g-n", "g-m"]),
  Exercise(id: "e-son-n-2", lessonId: "l-son-n", type: ExerciseType.wordRecognition, order: 2, correctItemId: "w-nez", itemIds: ["w-nez", "w-ami", "w-bebe"]),
  Exercise(id: "e-son-n-3", lessonId: "l-son-n", type: ExerciseType.soundGrapheme, order: 3, phoneme: "n", cue: "n", itemIds: ["g-m", "g-n", "g-r"]),
  Exercise(id: "e-son-n-4", lessonId: "l-son-n", type: ExerciseType.wordRecognition, order: 4, correctItemId: "w-banane", itemIds: ["w-bateau", "w-bebe", "w-banane"]),
  Exercise(id: "e-son-d-1", lessonId: "l-son-d", type: ExerciseType.soundGrapheme, order: 1, phoneme: "d", cue: "d, comme dans domino", itemIds: ["g-b", "g-d"]),
  Exercise(id: "e-son-d-2", lessonId: "l-son-d", type: ExerciseType.wordRecognition, order: 2, correctItemId: "w-domino", itemIds: ["w-ballon", "w-banane", "w-domino"]),
  Exercise(id: "e-son-d-3", lessonId: "l-son-d", type: ExerciseType.soundGrapheme, order: 3, phoneme: "d", cue: "d", itemIds: ["g-d", "g-t", "g-b"]),
  Exercise(id: "e-son-d-4", lessonId: "l-son-d", type: ExerciseType.wordRecognition, order: 4, correctItemId: "w-dodo", itemIds: ["w-chat", "w-dodo", "w-bebe"]),
  Exercise(id: "e-son-f-1", lessonId: "l-son-f", type: ExerciseType.soundGrapheme, order: 1, phoneme: "f", cue: "f, comme dans fleur", itemIds: ["g-f", "g-v"]),
  Exercise(id: "e-son-f-2", lessonId: "l-son-f", type: ExerciseType.wordRecognition, order: 2, correctItemId: "w-fleur", itemIds: ["w-doigt", "w-fleur", "w-avion"]),
  Exercise(id: "e-son-f-3", lessonId: "l-son-f", type: ExerciseType.soundGrapheme, order: 3, phoneme: "f", cue: "f", itemIds: ["g-s", "g-v", "g-f"]),
  Exercise(id: "e-son-v-1", lessonId: "l-son-v", type: ExerciseType.soundGrapheme, order: 1, phoneme: "v", cue: "v, comme dans vélo", itemIds: ["g-f", "g-v"]),
  Exercise(id: "e-son-v-2", lessonId: "l-son-v", type: ExerciseType.wordRecognition, order: 2, correctItemId: "w-velo", itemIds: ["w-velo", "w-bebe", "w-chat"]),
  Exercise(id: "e-son-v-3", lessonId: "l-son-v", type: ExerciseType.soundGrapheme, order: 3, phoneme: "v", cue: "v", itemIds: ["g-f", "g-v", "g-b"]),
  Exercise(id: "e-son-v-4", lessonId: "l-son-v", type: ExerciseType.wordRecognition, order: 4, correctItemId: "w-cheval", itemIds: ["w-chat", "w-ballon", "w-cheval"]),
  Exercise(id: "e-son-b-1", lessonId: "l-son-b", type: ExerciseType.soundGrapheme, order: 1, phoneme: "b", cue: "b, comme dans ballon", itemIds: ["g-b", "g-d"]),
  Exercise(id: "e-son-b-2", lessonId: "l-son-b", type: ExerciseType.wordRecognition, order: 2, correctItemId: "w-ballon", itemIds: ["w-cheval", "w-domino", "w-ballon"]),
  Exercise(id: "e-son-b-3", lessonId: "l-son-b", type: ExerciseType.soundGrapheme, order: 3, phoneme: "b", cue: "b", itemIds: ["g-b", "g-p", "g-d"]),
  Exercise(id: "e-son-b-4", lessonId: "l-son-b", type: ExerciseType.wordRecognition, order: 4, correctItemId: "w-bonbon", itemIds: ["w-domino", "w-bonbon", "w-cheval"]),
  Exercise(id: "e-son-j-1", lessonId: "l-son-j", type: ExerciseType.soundGrapheme, order: 1, phoneme: "j", cue: "j, comme dans jupe", itemIds: ["g-s", "g-j"]),
  Exercise(id: "e-son-j-2", lessonId: "l-son-j", type: ExerciseType.wordRecognition, order: 2, correctItemId: "w-jupe", itemIds: ["w-chat", "w-jupe", "w-bebe"]),
  Exercise(id: "e-son-j-3", lessonId: "l-son-j", type: ExerciseType.soundGrapheme, order: 3, phoneme: "j", cue: "j", itemIds: ["g-v", "g-s", "g-j"]),
  Exercise(id: "e-bd-b1", lessonId: "l-bd-1", type: ExerciseType.soundGrapheme, order: 1, phoneme: "b", cue: "b, comme ballon", itemIds: ["g-b", "g-d"]),
  Exercise(id: "e-bd-d1", lessonId: "l-bd-1", type: ExerciseType.soundGrapheme, order: 2, phoneme: "d", cue: "d, comme doigt", itemIds: ["g-b", "g-d"]),
  Exercise(id: "e-bd-b2", lessonId: "l-bd-1", type: ExerciseType.soundGrapheme, order: 3, phoneme: "b", cue: "b, comme bébé", itemIds: ["g-d", "g-p", "g-b"]),
  Exercise(id: "e-bd-bon", lessonId: "l-bd-1", type: ExerciseType.wordRecognition, order: 4, correctItemId: "w-bon", itemIds: ["w-don", "w-bon"]),
  Exercise(id: "e-bd-dodo", lessonId: "l-bd-1", type: ExerciseType.wordRecognition, order: 5, correctItemId: "w-dodo", itemIds: ["w-bebe", "w-dodo", "w-ballon"]),
  Exercise(id: "e-pq-p1", lessonId: "l-pq-1", type: ExerciseType.soundGrapheme, order: 1, phoneme: "p", cue: "p, comme papa", itemIds: ["g-p", "g-q"]),
  Exercise(id: "e-pq-q1", lessonId: "l-pq-1", type: ExerciseType.soundGrapheme, order: 2, phoneme: "k", cue: "q, comme quatre", itemIds: ["g-p", "g-q"]),
  Exercise(id: "e-pq-p2", lessonId: "l-pq-1", type: ExerciseType.soundGrapheme, order: 3, phoneme: "p", cue: "p, comme pomme", itemIds: ["g-q", "g-b", "g-p"]),
  Exercise(id: "e-pq-quatre", lessonId: "l-pq-1", type: ExerciseType.wordRecognition, order: 4, correctItemId: "w-quatre", itemIds: ["w-pomme", "w-quatre", "w-poule"]),
  Exercise(id: "e-pq-coq", lessonId: "l-pq-1", type: ExerciseType.wordRecognition, order: 5, correctItemId: "w-coq", itemIds: ["w-coq", "w-poule", "w-papa"]),
  Exercise(id: "e-son-ch-1", lessonId: "l-son-ch", type: ExerciseType.soundGrapheme, order: 1, phoneme: "ch", cue: "che, comme dans chat", itemIds: ["g-ch", "g-s"]),
  Exercise(id: "e-son-ch-2", lessonId: "l-son-ch", type: ExerciseType.wordRecognition, order: 2, correctItemId: "w-chat", itemIds: ["w-chat", "w-bebe", "w-dodo"]),
  Exercise(id: "e-son-ch-3", lessonId: "l-son-ch", type: ExerciseType.soundGrapheme, order: 3, phoneme: "ch", cue: "che", itemIds: ["g-s", "g-ch", "g-j"]),
  Exercise(id: "e-son-ch-4", lessonId: "l-son-ch", type: ExerciseType.wordRecognition, order: 4, correctItemId: "w-cheval", itemIds: ["w-ballon", "w-banane", "w-cheval"]),
  Exercise(id: "e-son-ou-1", lessonId: "l-son-ou", type: ExerciseType.soundGrapheme, order: 1, phoneme: "ou", cue: "ou, comme dans loupe", itemIds: ["g-u", "g-ou"]),
  Exercise(id: "e-son-ou-2", lessonId: "l-son-ou", type: ExerciseType.wordRecognition, order: 2, correctItemId: "w-loupe", itemIds: ["w-lapin", "w-livre", "w-loupe"]),
  Exercise(id: "e-son-ou-3", lessonId: "l-son-ou", type: ExerciseType.soundGrapheme, order: 3, phoneme: "ou", cue: "ou", itemIds: ["g-ou", "g-o", "g-u"]),
  Exercise(id: "e-son-ou-4", lessonId: "l-son-ou", type: ExerciseType.wordRecognition, order: 4, correctItemId: "w-poule", itemIds: ["w-poisson", "w-poule", "w-pomme"]),
  Exercise(id: "e-syl-ma-1", lessonId: "l-syl-ma", type: ExerciseType.soundGrapheme, order: 1, phoneme: "ma", cue: "ma, comme dans maman", itemIds: ["s-ma", "s-pa"]),
  Exercise(id: "e-syl-ma-2", lessonId: "l-syl-ma", type: ExerciseType.soundGrapheme, order: 2, phoneme: "ma", cue: "ma", itemIds: ["s-am", "s-ma"]),
  Exercise(id: "e-syl-ma-3", lessonId: "l-syl-ma", type: ExerciseType.soundGrapheme, order: 3, phoneme: "ma", cue: "ma", itemIds: ["s-pa", "s-mi", "s-ma"]),
  Exercise(id: "e-syl-ma-4", lessonId: "l-syl-ma", type: ExerciseType.wordRecognition, order: 4, correctItemId: "w-maman", itemIds: ["w-avion", "w-maman", "w-maison"]),
  Exercise(id: "e-syl-pa-1", lessonId: "l-syl-pa", type: ExerciseType.soundGrapheme, order: 1, phoneme: "pa", cue: "pa, comme dans papa", itemIds: ["s-ta", "s-pa"]),
  Exercise(id: "e-syl-pa-2", lessonId: "l-syl-pa", type: ExerciseType.soundGrapheme, order: 2, phoneme: "pa", cue: "pa", itemIds: ["s-pa", "s-ap"]),
  Exercise(id: "e-syl-pa-3", lessonId: "l-syl-pa", type: ExerciseType.soundGrapheme, order: 3, phoneme: "pa", cue: "pa", itemIds: ["s-pi", "s-pa", "s-ta"]),
  Exercise(id: "e-syl-pa-4", lessonId: "l-syl-pa", type: ExerciseType.wordRecognition, order: 4, correctItemId: "w-papa", itemIds: ["w-papa", "w-pomme", "w-poule"]),
  Exercise(id: "e-syl-ta-1", lessonId: "l-syl-ta", type: ExerciseType.soundGrapheme, order: 1, phoneme: "ta", cue: "ta", itemIds: ["s-ta", "s-la"]),
  Exercise(id: "e-syl-ta-2", lessonId: "l-syl-ta", type: ExerciseType.soundGrapheme, order: 2, phoneme: "ta", cue: "ta", itemIds: ["s-at", "s-ta"]),
  Exercise(id: "e-syl-ta-3", lessonId: "l-syl-ta", type: ExerciseType.soundGrapheme, order: 3, phoneme: "ta", cue: "ta", itemIds: ["s-ta", "s-la", "s-ti"]),
  Exercise(id: "e-syl-la-1", lessonId: "l-syl-la", type: ExerciseType.soundGrapheme, order: 1, phoneme: "la", cue: "la, comme dans lapin", itemIds: ["s-ta", "s-la"]),
  Exercise(id: "e-syl-la-2", lessonId: "l-syl-la", type: ExerciseType.soundGrapheme, order: 2, phoneme: "la", cue: "la", itemIds: ["s-la", "s-al"]),
  Exercise(id: "e-syl-la-3", lessonId: "l-syl-la", type: ExerciseType.soundGrapheme, order: 3, phoneme: "la", cue: "la", itemIds: ["s-ta", "s-li", "s-la"]),
  Exercise(id: "e-syl-la-4", lessonId: "l-syl-la", type: ExerciseType.wordRecognition, order: 4, correctItemId: "w-lapin", itemIds: ["w-loupe", "w-lapin", "w-livre"]),
  Exercise(id: "e-syl-mi-1", lessonId: "l-syl-mi", type: ExerciseType.soundGrapheme, order: 1, phoneme: "mi", cue: "mi, comme dans ami", itemIds: ["s-mi", "s-pi"]),
  Exercise(id: "e-syl-mi-2", lessonId: "l-syl-mi", type: ExerciseType.soundGrapheme, order: 2, phoneme: "mi", cue: "mi", itemIds: ["s-im", "s-mi"]),
  Exercise(id: "e-syl-mi-3", lessonId: "l-syl-mi", type: ExerciseType.soundGrapheme, order: 3, phoneme: "mi", cue: "mi", itemIds: ["s-mo", "s-mi", "s-pi"]),
  Exercise(id: "e-syl-mi-4", lessonId: "l-syl-mi", type: ExerciseType.wordRecognition, order: 4, correctItemId: "w-ami", itemIds: ["w-ami", "w-avion", "w-nez"]),
  Exercise(id: "e-syl-pi-1", lessonId: "l-syl-pi", type: ExerciseType.soundGrapheme, order: 1, phoneme: "pi", cue: "pi", itemIds: ["s-ti", "s-pi"]),
  Exercise(id: "e-syl-pi-2", lessonId: "l-syl-pi", type: ExerciseType.soundGrapheme, order: 2, phoneme: "pi", cue: "pi", itemIds: ["s-pi", "s-ip"]),
  Exercise(id: "e-syl-pi-3", lessonId: "l-syl-pi", type: ExerciseType.soundGrapheme, order: 3, phoneme: "pi", cue: "pi", itemIds: ["s-pi", "s-ti", "s-pa"]),
  Exercise(id: "e-syl-ti-1", lessonId: "l-syl-ti", type: ExerciseType.soundGrapheme, order: 1, phoneme: "ti", cue: "ti", itemIds: ["s-ti", "s-li"]),
  Exercise(id: "e-syl-ti-2", lessonId: "l-syl-ti", type: ExerciseType.soundGrapheme, order: 2, phoneme: "ti", cue: "ti", itemIds: ["s-it", "s-ti"]),
  Exercise(id: "e-syl-ti-3", lessonId: "l-syl-ti", type: ExerciseType.soundGrapheme, order: 3, phoneme: "ti", cue: "ti", itemIds: ["s-li", "s-to", "s-ti"]),
  Exercise(id: "e-syl-li-1", lessonId: "l-syl-li", type: ExerciseType.soundGrapheme, order: 1, phoneme: "li", cue: "li, comme dans livre", itemIds: ["s-mi", "s-li"]),
  Exercise(id: "e-syl-li-2", lessonId: "l-syl-li", type: ExerciseType.soundGrapheme, order: 2, phoneme: "li", cue: "li", itemIds: ["s-li", "s-il"]),
  Exercise(id: "e-syl-li-3", lessonId: "l-syl-li", type: ExerciseType.soundGrapheme, order: 3, phoneme: "li", cue: "li", itemIds: ["s-la", "s-li", "s-mi"]),
  Exercise(id: "e-syl-li-4", lessonId: "l-syl-li", type: ExerciseType.wordRecognition, order: 4, correctItemId: "w-livre", itemIds: ["w-livre", "w-lion", "w-lapin"]),
  Exercise(id: "e-syl-mo-1", lessonId: "l-syl-mo", type: ExerciseType.soundGrapheme, order: 1, phoneme: "mo", cue: "mo", itemIds: ["s-mo", "s-to"]),
  Exercise(id: "e-syl-mo-2", lessonId: "l-syl-mo", type: ExerciseType.soundGrapheme, order: 2, phoneme: "mo", cue: "mo", itemIds: ["s-om", "s-mo"]),
  Exercise(id: "e-syl-mo-3", lessonId: "l-syl-mo", type: ExerciseType.soundGrapheme, order: 3, phoneme: "mo", cue: "mo", itemIds: ["s-mo", "s-to", "s-ma"]),
  Exercise(id: "e-syl-to-1", lessonId: "l-syl-to", type: ExerciseType.soundGrapheme, order: 1, phoneme: "to", cue: "to", itemIds: ["s-mo", "s-to"]),
  Exercise(id: "e-syl-to-2", lessonId: "l-syl-to", type: ExerciseType.soundGrapheme, order: 2, phoneme: "to", cue: "to", itemIds: ["s-to", "s-ot"]),
  Exercise(id: "e-syl-to-3", lessonId: "l-syl-to", type: ExerciseType.soundGrapheme, order: 3, phoneme: "to", cue: "to", itemIds: ["s-mo", "s-ti", "s-to"]),
  Exercise(id: "e-mot-maman-1", lessonId: "l-mot-maman", type: ExerciseType.wordRecognition, order: 1, correctItemId: "w-maman", itemIds: ["w-maman", "w-maison", "w-avion"]),
  Exercise(id: "e-mot-maman-2", lessonId: "l-mot-maman", type: ExerciseType.wordRecognition, order: 2, correctItemId: "w-maman", itemIds: ["w-doigt", "w-maman", "w-ecole"]),
  Exercise(id: "e-mot-maman-3", lessonId: "l-mot-maman", type: ExerciseType.wordRecognition, order: 3, correctItemId: "w-maman", itemIds: ["x-naman", "w-maman"]),
  Exercise(id: "e-mot-papa-1", lessonId: "l-mot-papa", type: ExerciseType.wordRecognition, order: 1, correctItemId: "w-papa", itemIds: ["w-pomme", "w-poule", "w-papa"]),
  Exercise(id: "e-mot-papa-2", lessonId: "l-mot-papa", type: ExerciseType.wordRecognition, order: 2, correctItemId: "w-papa", itemIds: ["w-papa", "w-chat", "w-bebe"]),
  Exercise(id: "e-mot-papa-3", lessonId: "l-mot-papa", type: ExerciseType.wordRecognition, order: 3, correctItemId: "w-papa", itemIds: ["w-papa", "x-qapa"]),
  Exercise(id: "e-mot-livre-1", lessonId: "l-mot-livre", type: ExerciseType.wordRecognition, order: 1, correctItemId: "w-livre", itemIds: ["w-lapin", "w-livre", "w-lion"]),
  Exercise(id: "e-mot-livre-2", lessonId: "l-mot-livre", type: ExerciseType.wordRecognition, order: 2, correctItemId: "w-livre", itemIds: ["w-lune", "w-loupe", "w-livre"]),
  Exercise(id: "e-mot-livre-3", lessonId: "l-mot-livre", type: ExerciseType.wordRecognition, order: 3, correctItemId: "w-livre", itemIds: ["x-tivre", "w-livre"]),
  Exercise(id: "e-mot-ecole-1", lessonId: "l-mot-ecole", type: ExerciseType.wordRecognition, order: 1, correctItemId: "w-ecole", itemIds: ["w-ecole", "w-avion", "w-doigt"]),
  Exercise(id: "e-mot-ecole-2", lessonId: "l-mot-ecole", type: ExerciseType.wordRecognition, order: 2, correctItemId: "w-ecole", itemIds: ["w-elephant", "w-ecole", "w-fleur"]),
  Exercise(id: "e-mot-ecole-3", lessonId: "l-mot-ecole", type: ExerciseType.wordRecognition, order: 3, correctItemId: "w-ecole", itemIds: ["w-ecole", "x-ecole"]),
  Exercise(id: "e-mot-maison-1", lessonId: "l-mot-maison", type: ExerciseType.wordRecognition, order: 1, correctItemId: "w-maison", itemIds: ["w-maman", "w-ballon", "w-maison"]),
  Exercise(id: "e-mot-maison-2", lessonId: "l-mot-maison", type: ExerciseType.wordRecognition, order: 2, correctItemId: "w-maison", itemIds: ["w-maison", "w-bateau", "w-banane"]),
  Exercise(id: "e-mot-maison-3", lessonId: "l-mot-maison", type: ExerciseType.wordRecognition, order: 3, correctItemId: "w-maison", itemIds: ["x-naison", "w-maison"]),
  Exercise(id: "e-mot-ami-1", lessonId: "l-mot-ami", type: ExerciseType.wordRecognition, order: 1, correctItemId: "w-ami", itemIds: ["w-nez", "w-ami", "w-avion"]),
  Exercise(id: "e-mot-ami-2", lessonId: "l-mot-ami", type: ExerciseType.wordRecognition, order: 2, correctItemId: "w-ami", itemIds: ["w-chat", "w-bebe", "w-ami"]),
  Exercise(id: "e-mot-ami-3", lessonId: "l-mot-ami", type: ExerciseType.wordRecognition, order: 3, correctItemId: "w-ami", itemIds: ["w-ami", "x-omi"]),
  Exercise(id: "e-mot-chat-1", lessonId: "l-mot-chat", type: ExerciseType.wordRecognition, order: 1, correctItemId: "w-chat", itemIds: ["w-chat", "w-cheval", "w-bebe"]),
  Exercise(id: "e-mot-chat-2", lessonId: "l-mot-chat", type: ExerciseType.wordRecognition, order: 2, correctItemId: "w-chat", itemIds: ["w-dodo", "w-chat", "w-jupe"]),
  Exercise(id: "e-mot-chat-3", lessonId: "l-mot-chat", type: ExerciseType.wordRecognition, order: 3, correctItemId: "w-chat", itemIds: ["x-chot", "w-chat"]),
  Exercise(id: "e-mot-lune-1", lessonId: "l-mot-lune", type: ExerciseType.wordRecognition, order: 1, correctItemId: "w-lune", itemIds: ["w-lion", "w-lapin", "w-lune"]),
  Exercise(id: "e-mot-lune-2", lessonId: "l-mot-lune", type: ExerciseType.wordRecognition, order: 2, correctItemId: "w-lune", itemIds: ["w-lune", "w-loupe", "w-livre"]),
  Exercise(id: "e-mot-lune-3", lessonId: "l-mot-lune", type: ExerciseType.wordRecognition, order: 3, correctItemId: "w-lune", itemIds: ["w-lune", "x-tune"]),
  Exercise(id: "e-mot-fleur-1", lessonId: "l-mot-fleur", type: ExerciseType.wordRecognition, order: 1, correctItemId: "w-fleur", itemIds: ["w-doigt", "w-fleur", "w-avion"]),
  Exercise(id: "e-mot-fleur-2", lessonId: "l-mot-fleur", type: ExerciseType.wordRecognition, order: 2, correctItemId: "w-fleur", itemIds: ["w-lapin", "w-ecole", "w-fleur"]),
  Exercise(id: "e-mot-fleur-3", lessonId: "l-mot-fleur", type: ExerciseType.wordRecognition, order: 3, correctItemId: "w-fleur", itemIds: ["x-tleur", "w-fleur"]),
  Exercise(id: "e-mot-velo-1", lessonId: "l-mot-velo", type: ExerciseType.wordRecognition, order: 1, correctItemId: "w-velo", itemIds: ["w-velo", "w-bebe", "w-chat"]),
  Exercise(id: "e-mot-velo-2", lessonId: "l-mot-velo", type: ExerciseType.wordRecognition, order: 2, correctItemId: "w-velo", itemIds: ["w-dodo", "w-velo", "w-jupe"]),
  Exercise(id: "e-mot-velo-3", lessonId: "l-mot-velo", type: ExerciseType.wordRecognition, order: 3, correctItemId: "w-velo", itemIds: ["w-velo", "x-uelo"]),
  Exercise(id: "e-son-oi-1", lessonId: "l-son-oi", type: ExerciseType.soundGrapheme, order: 1, phoneme: "oi", cue: "oi, comme dans poisson", itemIds: ["g-oi", "g-ou"]),
  Exercise(id: "e-son-oi-2", lessonId: "l-son-oi", type: ExerciseType.wordRecognition, order: 2, correctItemId: "w-poisson", itemIds: ["w-pomme", "w-poule", "w-poisson"]),
  Exercise(id: "e-son-oi-3", lessonId: "l-son-oi", type: ExerciseType.soundGrapheme, order: 3, phoneme: "oi", cue: "oi", itemIds: ["g-oi", "g-o", "g-ou"]),
  Exercise(id: "e-son-oi-4", lessonId: "l-son-oi", type: ExerciseType.wordRecognition, order: 4, correctItemId: "w-doigt", itemIds: ["w-domino", "w-doigt", "w-dodo"]),
  Exercise(id: "e-son-an-1", lessonId: "l-son-an", type: ExerciseType.soundGrapheme, order: 1, phoneme: "an", cue: "an, comme dans maman", itemIds: ["g-on", "g-an"]),
  Exercise(id: "e-son-an-2", lessonId: "l-son-an", type: ExerciseType.wordRecognition, order: 2, correctItemId: "w-maman", itemIds: ["w-avion", "w-maman", "w-maison"]),
  Exercise(id: "e-son-an-3", lessonId: "l-son-an", type: ExerciseType.soundGrapheme, order: 3, phoneme: "an", cue: "an", itemIds: ["g-in", "g-on", "g-an"]),
  Exercise(id: "e-son-an-4", lessonId: "l-son-an", type: ExerciseType.wordRecognition, order: 4, correctItemId: "w-elephant", itemIds: ["w-elephant", "w-ecole", "w-poisson"]),
  Exercise(id: "e-son-on-1", lessonId: "l-son-on", type: ExerciseType.soundGrapheme, order: 1, phoneme: "on", cue: "on, comme dans bonbon", itemIds: ["g-on", "g-an"]),
  Exercise(id: "e-son-on-2", lessonId: "l-son-on", type: ExerciseType.wordRecognition, order: 2, correctItemId: "w-bonbon", itemIds: ["w-bonbon", "w-banane", "w-bateau"]),
  Exercise(id: "e-son-on-3", lessonId: "l-son-on", type: ExerciseType.soundGrapheme, order: 3, phoneme: "on", cue: "on", itemIds: ["g-an", "g-on", "g-ou"]),
  Exercise(id: "e-son-on-4", lessonId: "l-son-on", type: ExerciseType.wordRecognition, order: 4, correctItemId: "w-lion", itemIds: ["w-livre", "w-lune", "w-lion"]),
  Exercise(id: "e-son-in-1", lessonId: "l-son-in", type: ExerciseType.soundGrapheme, order: 1, phoneme: "in", cue: "in, comme dans lapin", itemIds: ["g-an", "g-in"]),
  Exercise(id: "e-son-in-2", lessonId: "l-son-in", type: ExerciseType.wordRecognition, order: 2, correctItemId: "w-lapin", itemIds: ["w-livre", "w-loupe", "w-lapin"]),
  Exercise(id: "e-son-in-3", lessonId: "l-son-in", type: ExerciseType.soundGrapheme, order: 3, phoneme: "in", cue: "in", itemIds: ["g-in", "g-on", "g-an"]),
  Exercise(id: "e-son-eau-1", lessonId: "l-son-eau", type: ExerciseType.soundGrapheme, order: 1, phoneme: "eau", cue: "eau, comme dans bateau", itemIds: ["g-eau", "g-o"]),
  Exercise(id: "e-son-eau-2", lessonId: "l-son-eau", type: ExerciseType.wordRecognition, order: 2, correctItemId: "w-bateau", itemIds: ["w-banane", "w-bateau", "w-ballon"]),
  Exercise(id: "e-son-eau-3", lessonId: "l-son-eau", type: ExerciseType.soundGrapheme, order: 3, phoneme: "eau", cue: "eau", itemIds: ["g-ou", "g-o", "g-eau"]),
  Exercise(id: "e-phrase-1-1", lessonId: "l-phrase-1", type: ExerciseType.wordRecognition, order: 1, correctItemId: "p-1", itemIds: ["p-1", "p-2", "p-3"]),
  Exercise(id: "e-phrase-1-2", lessonId: "l-phrase-1", type: ExerciseType.wordRecognition, order: 2, correctItemId: "w-chat", itemIds: ["w-le", "w-chat", "w-dort"]),
  Exercise(id: "e-phrase-1-3", lessonId: "l-phrase-1", type: ExerciseType.wordRecognition, order: 3, correctItemId: "w-dort", itemIds: ["w-le", "w-chat", "w-dort"]),
  Exercise(id: "e-phrase-2-1", lessonId: "l-phrase-2", type: ExerciseType.wordRecognition, order: 1, correctItemId: "p-2", itemIds: ["p-3", "p-4", "p-2"]),
  Exercise(id: "e-phrase-2-2", lessonId: "l-phrase-2", type: ExerciseType.wordRecognition, order: 2, correctItemId: "w-livre", itemIds: ["w-papa", "w-lit", "w-un", "w-livre"]),
  Exercise(id: "e-phrase-2-3", lessonId: "l-phrase-2", type: ExerciseType.wordRecognition, order: 3, correctItemId: "w-lit", itemIds: ["w-papa", "w-lit", "w-un", "w-livre"]),
  Exercise(id: "e-phrase-3-1", lessonId: "l-phrase-3", type: ExerciseType.wordRecognition, order: 1, correctItemId: "p-3", itemIds: ["p-5", "p-3", "p-4"]),
  Exercise(id: "e-phrase-3-2", lessonId: "l-phrase-3", type: ExerciseType.wordRecognition, order: 2, correctItemId: "w-lune", itemIds: ["w-la", "w-lune", "w-est", "w-belle"]),
  Exercise(id: "e-phrase-3-3", lessonId: "l-phrase-3", type: ExerciseType.wordRecognition, order: 3, correctItemId: "w-belle", itemIds: ["w-la", "w-lune", "w-est", "w-belle"]),
  Exercise(id: "e-phrase-4-1", lessonId: "l-phrase-4", type: ExerciseType.wordRecognition, order: 1, correctItemId: "p-4", itemIds: ["p-4", "p-5", "p-1"]),
  Exercise(id: "e-phrase-4-2", lessonId: "l-phrase-4", type: ExerciseType.wordRecognition, order: 2, correctItemId: "w-fleurs", itemIds: ["w-maman", "w-aime", "w-les", "w-fleurs"]),
  Exercise(id: "e-phrase-4-3", lessonId: "l-phrase-4", type: ExerciseType.wordRecognition, order: 3, correctItemId: "w-aime", itemIds: ["w-maman", "w-aime", "w-les", "w-fleurs"]),
  Exercise(id: "e-phrase-5-1", lessonId: "l-phrase-5", type: ExerciseType.wordRecognition, order: 1, correctItemId: "p-5", itemIds: ["p-1", "p-2", "p-5"]),
  Exercise(id: "e-phrase-5-2", lessonId: "l-phrase-5", type: ExerciseType.wordRecognition, order: 2, correctItemId: "w-ecole", itemIds: ["w-je", "w-vais", "w-a", "w-ecole"]),
  Exercise(id: "e-phrase-5-3", lessonId: "l-phrase-5", type: ExerciseType.wordRecognition, order: 3, correctItemId: "w-vais", itemIds: ["w-je", "w-vais", "w-a", "w-ecole"]),
];
